name: Prepare and Upload Artifact

on:
  workflow_call:
    inputs:
      newSha:
        required: false
        type: string
    secrets:
      projectId:
        required: true
      umbracoCloudApiKey:
        required: true
    outputs:
      artifactId:
        description: 'The Id of the uploaded artifact'
        value: ${{ jobs.uploadArtifact.outputs.artifactId }}

jobs:
  prepareDeployment:
    name: Prepare Deployment to cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.newSha }}

      # switch the gitignore files so cloud does not ignore the build frontend assets
      - name: Prepare Cloud Git Ignore
        run: cp cloud.gitignore .gitignore
        shell: bash

      # zip everything, except what is defined in the 'cloud.zipignore'
      - name: Zip Source Code
        run: zip -r sources.zip . -x@cloud.zipignore
        shell: bash

      - name: Store package for upload
        uses: actions/upload-artifact@v4
        with:
          name: source-artifact
          path: ${{GITHUB.WORKSPACE}}/sources.zip
          retention-days: 1

  uploadArtifact:
    name: Upload Source
    runs-on: ubuntu-latest
    needs: prepareDeployment
    outputs:
      artifactId: ${{ steps.upload-artifact.outputs.artifactId }}
    steps:
      - uses: actions/checkout@v4

      - name: Get package for upload
        uses: actions/download-artifact@v4
        with:
            name: source-artifact

      # Upload your zipped artifact
      - name: Post Zipped Artifact
        id: upload-artifact
        shell: pwsh
        run: >
          ${{GITHUB.WORKSPACE}}/.github/powershell/Add-DeploymentArtifact.ps1 
          -ProjectId ${{ secrets.projectId }} 
          -ApiKey ${{ secrets.umbracoCloudApiKey }} 
          -FilePath ${{ GITHUB.WORKSPACE }}/sources.zip
          -Description "Artifact for ${{github.run_number}}"
          -Version "${{github.run_number}}"
          -PipelineVendor GITHUB